---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, FAS, ASA, all-flash, ONTAP 
summary: NetApp의 ONTAP 스토리지 시스템 제품군은 엔터프라이즈급 안정성과 지속적인 데이터 액세스 기능을 갖춘 신속하고 안전한 스토리지가 필요한 엔터프라이즈 애플리케이션을 위해 설계되었습니다. 
---
= ONTAP 하드웨어 시스템에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp의 ONTAP 하드웨어 시스템은 엔터프라이즈급 안정성과 지속적인 데이터 액세스 기능을 갖춘, 관리가 간편하고 빠르며 안전한 스토리지가 필요한 엔터프라이즈 애플리케이션을 위해 설계되었습니다.

NetApp의 ONTAP 하드웨어 시스템은 All-Flash(AFF) 및 하이브리드 플래시 및 FAS(HDD 전용) 구성으로 제공되므로 성능, 용량 및 비용 요구사항을 가장 잘 충족하는 혼합 스토리지 미디어를 선택할 수 있습니다.

다양한 모델 조합을 클러스터링하여 동일한 스토리지 시스템에서 혼합 워크로드를 실행하고 최신 기술을 갖춘 새로운 세대의 스토리지를 추가하여 환경을 확장할 수 있습니다.



== AFF(All Flash FAS) 시스템

NVMe 기반 AFF 시스템은 가상화 환경을 위해 구축된 강력한 스케일아웃 플랫폼으로, NetApp ONTAP 구성에서 독립 시스템 또는 고성능 계층으로 구축할 수 있습니다.

All-Flash FAS 구성은 고성능, 짧은 지연 시간, 안정성이 요구되는 다양한 워크로드, 특히 VDI 및 데이터베이스를 지원하는 비즈니스 크리티컬 애플리케이션에 이상적인 솔루션입니다.

* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A-Series 데이터시트를 읽어 보십시오"^]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C-Series 데이터시트를 읽어 보십시오"^]




== ASA(All Flash SAN 어레이) 시스템

NetApp ASA(All-Flash SAN 어레이)는 FCP 또는 iSCSI 프로토콜을 통해 엔터프라이즈 미션 크리티컬 데이터베이스 및 기타 SAN 워크로드에 지속적인 데이터 가용성을 제공하는 단순화된 전용 SAN 경험을 제공합니다.

.ASA r2 시스템
새로운 NetApp ASA R2 시스템(ASA A1K, ASA A70 및 ASA A90)은 SAN 전용 고객의 요구 사항에 맞는 간소화된 환경을 제공하는 통합된 하드웨어 및 소프트웨어 솔루션을 제공합니다.

ASA R2 시스템에서 ONTAP 소프트웨어 및 System Manager를 간소화하여 필수 SAN 기능을 지원하는 동시에 SAN 환경에서 지원되지 않는 기능에 대한 가시성을 제거합니다.

* https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA 데이터시트를 읽어 보십시오"^]
* 에 대해 자세히 알아보십시오 link:https://docs.netapp.com/us-en/asa-r2/learn-more/hardware-comparison.html["새로운 ASA R2 시스템을 ASA 시스템과 비교"^]
* 에서 ASA 및 ASA R2 시스템에 대한 전체 구성 지원 및 제한 사항을 참조하십시오 https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]




== FAS 하이브리드 플래시 시스템

FAS 하이브리드 플래시 시스템은 강력한 데이터 관리와 쉬운 클라우드 연결이 필요한 공유 통합 SAN 및 NAS 환경을 위해 만들어진 하드웨어 플랫폼입니다.

FAS 하이브리드 플래시 시스템은 가용성이 높은 하드웨어를 통해 플래시 드라이브와 기존 회전식 드라이브를 이상적으로 결합하여 워크로드 요구사항을 비용 효율적으로 충족합니다. 백업 및 보존, 일반 비즈니스 애플리케이션 통합 및 분산 콘텐츠에 이상적입니다.

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS 데이터시트를 읽어 보십시오"^]



== MetroCluster

ONTAP의 MetroCluster 기능으로 구성된 ONTAP의 하드웨어 스토리지 시스템은 어레이 기반 클러스터링을 동기식 복제와 결합하여 지속적인 가용성과 데이터 무손실을 실현하는 솔루션을 제공합니다. MetroCluster 구성은 모든 미션 크리티컬 데이터를 트랜잭션별로 즉시 복제하므로 애플리케이션과 데이터에 중단 없이 액세스할 수 있도록 지원합니다.

표준 데이터 복제 솔루션과 달리 MetroCluster는 호스트 환경에서 원활하게 작동하여 지속적인 데이터 가용성을 제공하고, 복잡한 페일오버 스크립트를 생성하고 유지할 필요가 없습니다.

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["MetroCluster에 대해 자세히 알아보십시오"^]



== ONTAP 소프트웨어

ONTAP 데이터 관리 소프트웨어는 ONTAP 하드웨어 시스템을 구동하는 클러스터 스토리지 소프트웨어입니다. ONTAP 소프트웨어는 모든 유형의 하드웨어 노드를 최대 24개까지 지원하는 글로벌 네임스페이스를 통해 유니파이드 스토리지(블록 및 파일)를 지원하므로, ONTAP System Manager GUI를 사용하여 상당한 워크로드 통합을 관리할 수 있습니다.

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["ONTAP 소프트웨어 데이터시트를 읽어 보십시오"^]

.를 참조하십시오
* https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAP 하드웨어 시스템 설명서"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster 문서"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP 문서"^]

